CREATE TABLE dev.driversDirectory (
  id INT PRIMARY KEY,
  driverId VARCHAR(100),
  status VARCHAR(100),
  firstName VARCHAR(100),
  lastName VARCHAR(100),
  truckId VARCHAR(100),
  phoneNumber BIGINT, 
  email VARCHAR(100),
  hiredOn DATE,        
  updatedOn DATE,     
  companyId VARCHAR(100), 
  dispatcher VARCHAR(100),
  firstLanguage VARCHAR(100),
  secondLanguage VARCHAR(100),
  globalDnd BOOLEAN,
  safetyCall BOOLEAN,
  safetyMessage BOOLEAN,
  hosSupport BOOLEAN,
  maintainanceCall BOOLEAN,
  maintainanceMessage BOOLEAN,
  dispatchCall BOOLEAN,
  dispatchMessage BOOLEAN,
  accountCall BOOLEAN,
  accountMessage BOOLEAN
);
