CREATE TABLE dev.driversDirectory (
  driverId VARCHAR(100) PRIMARY KEY,
  status VARCHAR(100),
  firstName VARCHAR(100),
  lastName VARCHAR(100),
  truckId VARCHAR(100),
  phoneNumber VARCHAR(100), 
  email VARCHAR(100),
  hiredOn VARCHAR(100),        
  updatedOn VARCHAR(100),     
  companyId VARCHAR(100), 
  dispatcher VARCHAR(100),
  firstLanguage VARCHAR(100),
  secondLanguage VARCHAR(100),
  globalDnd BOOLEAN,
  safetyCall BOOLEAN,
  safetyMessage BOOLEAN,
  hosSupport BOOLEAN,
  maintainanceCall BOOLEAN,
  maintainanceMessage BOOLEAN,
  dispatchCall BOOLEAN,
  dispatchMessage BOOLEAN,
  accountCall BOOLEAN,
  accountMessage BOOLEAN
);
